pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"org/appliedtopology/tda4s.html#","e":false,"i":"","n":"org.appliedtopology.tda4s","t":"org.appliedtopology.tda4s","d":"","k":"package","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#","e":false,"i":"","n":"Chain","t":"Chain(entries: SortedMap[Set[Int], Double])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#isZero-0","e":false,"i":"","n":"isZero","t":"isZero: Boolean","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#scaleAdd-fffff0f9","e":false,"i":"","n":"scaleAdd","t":"scaleAdd(scale: Double, other: Chain): Chain","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#","e":false,"i":"","n":"Chain","t":"Chain","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#boundary-fffff193","e":false,"i":"","n":"boundary","t":"boundary(simplex: Set[Int])(ordering: Ordering[Set[Int]]): Chain","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#reduceBy-fffff519","e":false,"i":"","n":"reduceBy","t":"reduceBy(chain: Chain, basis: Map[Set[Int], Chain], log: Map[Set[Int], Double] = ...): (Chain, Map[Set[Int], Double])","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#","e":false,"i":"","n":"Field","t":"Field","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#*-fffffab9","e":false,"i":"extension (x: Self)","n":"*","t":"*(y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#+-fffffab9","e":false,"i":"extension (x: Self)","n":"+","t":"+(y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#--fffffab9","e":false,"i":"extension (x: Self)","n":"-","t":"-(y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#/-fffffab9","e":false,"i":"extension (x: Self)","n":"/","t":"/(y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#Self-0","e":false,"i":"","n":"Self","t":"Self","d":"org.appliedtopology.tda4s.Field","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#add-fffffab9","e":false,"i":"","n":"add","t":"add(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#apply-aba","e":false,"i":"","n":"apply","t":"apply(x: Int): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#div-fffffab9","e":false,"i":"","n":"div","t":"div(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#mul-fffffab9","e":false,"i":"","n":"mul","t":"mul(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#one-0","e":false,"i":"","n":"one","t":"one: Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#sub-fffffab9","e":false,"i":"","n":"sub","t":"sub(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#zero-0","e":false,"i":"","n":"zero","t":"zero: Self","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$.html#","e":false,"i":"","n":"Field","t":"Field","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Field$.html#apply-fffff2c9","e":false,"i":"","n":"apply","t":"apply(p: Int): Field","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$.html#given_is_Double_Field-0","e":false,"i":"","n":"given_is_Double_Field","t":"given_is_Double_Field: is[Double, Field]","d":"org.appliedtopology.tda4s.Field","k":"given","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#","e":false,"i":"","n":"FiniteField","t":"FiniteField(p: Int) extends Field","d":"org.appliedtopology.tda4s.Field","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#Self-0","e":false,"i":"","n":"Self","t":"Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#add-f47","e":false,"i":"","n":"add","t":"add(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#div-f47","e":false,"i":"","n":"div","t":"div(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#given_ffp_is_field-0","e":false,"i":"","n":"given_ffp_is_field","t":"given_ffp_is_field: is[Self, Field]","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"given","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#mul-f47","e":false,"i":"","n":"mul","t":"mul(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#one-0","e":false,"i":"","n":"one","t":"one: Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#sub-f47","e":false,"i":"","n":"sub","t":"sub(x: Self, y: Self): Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#toString-78c","e":false,"i":"extension (x: Self)","n":"toString","t":"toString: String","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#unapply-fffff2e4","e":false,"i":"","n":"unapply","t":"unapply(x: Self): Option[Int]","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$$FiniteField.html#zero-0","e":false,"i":"","n":"zero","t":"zero: Self","d":"org.appliedtopology.tda4s.Field.FiniteField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#","e":false,"i":"","n":"NaivePersistentHomology","t":"NaivePersistentHomology(simplexstream: Seq[Set[Int]], filtrationValues: Map[Set[Int], Double])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#barcode-0","e":false,"i":"","n":"barcode","t":"barcode: Seq[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#barcodes-0","e":false,"i":"","n":"barcodes","t":"barcodes: ListBuffer[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#state-0","e":false,"i":"","n":"state","t":"state: State","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"var","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#step-fffff1fa","e":false,"i":"","n":"step","t":"step(simplex: Set[Int]): Unit","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology$State.html#","e":false,"i":"","n":"State","t":"State(cycleBasis: Map[Set[Int], Chain], boundaryBasis: Map[Set[Int], Chain], coboundaryLookup: Map[Set[Int], Set[Int]], cycleBirths: Map[Set[Int], Double])","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/PersistentHomology$.html#","e":false,"i":"","n":"PersistentHomology","t":"PersistentHomology","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/PersistentHomology$.html#persistentHomology-fffff6fe","e":false,"i":"","n":"persistentHomology","t":"persistentHomology(simplexstream: Seq[Set[Int]], filtrationValues: Map[Set[Int], Double]): Seq[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.PersistentHomology","k":"def","x":""}];