pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"org/appliedtopology/tda4s.html#","e":false,"i":"","n":"org.appliedtopology.tda4s","t":"org.appliedtopology.tda4s","d":"","k":"package","x":""},
{"l":"org/appliedtopology/tda4s.html#Alpha-767","e":false,"i":"","n":"Alpha","t":"Alpha(pts: Seq[Array[Double]])(using epsilon: Epsilon): SimplexStream","d":"org.appliedtopology.tda4s","k":"def","x":""},
{"l":"org/appliedtopology/tda4s.html#Point-0","e":false,"i":"","n":"Point","t":"Point = RealVector","d":"org.appliedtopology.tda4s","k":"type","x":""},
{"l":"org/appliedtopology/tda4s.html#given_Epsilon-0","e":false,"i":"","n":"given_Epsilon","t":"given_Epsilon: Epsilon","d":"org.appliedtopology.tda4s","k":"given","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#","e":false,"i":"","n":"Chain","t":"Chain[T](using val field: Field[T])(val simplexCoefficients: SortedMap[Simplex, field.F])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#field-0","e":false,"i":"","n":"field","t":"field: Field[T]","d":"org.appliedtopology.tda4s.Chain","k":"given","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#isZero-0","e":false,"i":"","n":"isZero","t":"isZero: Boolean","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#leading-0","e":false,"i":"","n":"leading","t":"leading: Option[(Simplex, field.F)]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#scale-fffff0a4","e":false,"i":"","n":"scale","t":"scale(scalingFactor: field.F): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#scaleAdd-773","e":false,"i":"","n":"scaleAdd","t":"scaleAdd(scalingFactor: field.F, other: Chain[T]): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#simplexCoefficients-0","e":false,"i":"","n":"simplexCoefficients","t":"simplexCoefficients: SortedMap[Simplex, field.F]","d":"org.appliedtopology.tda4s.Chain","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#","e":false,"i":"","n":"Chain","t":"Chain","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#from-ffffffce","e":false,"i":"","n":"from","t":"from[T](simplex: Simplex)(ordering: Ordering[Simplex])(using field: Field[T]): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#from-2cf","e":false,"i":"","n":"from","t":"from[T](using field: Field[T])(terms: (Simplex, field.F)*)(using ordering: Ordering[Simplex]): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#reduce-fffff2e8","e":false,"i":"","n":"reduce","t":"reduce[T](chain: Chain[T], basis: Map[Simplex, Chain[T]])(using outerField: Field[T]): (Chain[T], Map[Simplex, outerField.F])","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DelaunaySimplex.html#","e":false,"i":"","n":"DelaunaySimplex","t":"DelaunaySimplex(simplex: Simplex, circumsphere: Hypersphere)","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/DistanceMatrixMetricSpace.html#","e":false,"i":"","n":"DistanceMatrixMetricSpace","t":"DistanceMatrixMetricSpace(matrix: Array[Array[Double]]) extends MetricSpace[Int]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#","e":false,"i":"","n":"DoubleIsField","t":"DoubleIsField(val eps: Double) extends Field[Double]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#add-44b","e":false,"i":"","n":"add","t":"add(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#div-44b","e":false,"i":"","n":"div","t":"div(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#eps-0","e":false,"i":"","n":"eps","t":"eps: Double","d":"org.appliedtopology.tda4s.DoubleIsField","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#inv-5b2","e":false,"i":"","n":"inv","t":"inv(x: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#mul-44b","e":false,"i":"","n":"mul","t":"mul(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#neg-5b2","e":false,"i":"","n":"neg","t":"neg(x: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#one-0","e":false,"i":"","n":"one","t":"one: F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#pow-647","e":false,"i":"","n":"pow","t":"pow(x: F, n: Int): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#repAdd-647","e":false,"i":"","n":"repAdd","t":"repAdd(x: F, n: Int): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#sub-44b","e":false,"i":"","n":"sub","t":"sub(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#zero-0","e":false,"i":"","n":"zero","t":"zero: F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Epsilon.html#","e":false,"i":"","n":"Epsilon","t":"Epsilon(epsilon: Double)","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#","e":false,"i":"","n":"Field","t":"Field[T]","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#*-fffffab9","e":false,"i":"extension (x: F)","n":"*","t":"*(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#*-fffffc87","e":false,"i":"extension (x: F)","n":"*","t":"*(n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#**-fffffc87","e":false,"i":"extension (x: F)","n":"**","t":"**(n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#+-fffffab9","e":false,"i":"extension (x: F)","n":"+","t":"+(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#--fffffab9","e":false,"i":"extension (x: F)","n":"-","t":"-(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#/-fffffab9","e":false,"i":"extension (x: F)","n":"/","t":"/(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#F-0","e":false,"i":"","n":"F","t":"F","d":"org.appliedtopology.tda4s.Field","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#add-fffffab9","e":false,"i":"","n":"add","t":"add(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#div-fffffab9","e":false,"i":"","n":"div","t":"div(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#equiv-fffff7fa","e":false,"i":"","n":"equiv","t":"equiv(x: F, y: F): Boolean","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#inv-d26","e":false,"i":"","n":"inv","t":"inv(x: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#isZero-4ad","e":false,"i":"","n":"isZero","t":"isZero(x: F): Boolean","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#mul-fffffab9","e":false,"i":"","n":"mul","t":"mul(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#neg-d26","e":false,"i":"","n":"neg","t":"neg(x: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#normalize-d26","e":false,"i":"","n":"normalize","t":"normalize(x: T): T","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#one-0","e":false,"i":"","n":"one","t":"one: F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#pow-fffffc87","e":false,"i":"","n":"pow","t":"pow(x: F, n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#repAdd-fffffc87","e":false,"i":"","n":"repAdd","t":"repAdd(x: F, n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#show-9f8","e":false,"i":"","n":"show","t":"show(x: F): String","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#sub-fffffab9","e":false,"i":"","n":"sub","t":"sub(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#unary_--d26","e":false,"i":"extension (x: F)","n":"unary_-","t":"unary_-: F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#zero-0","e":false,"i":"","n":"zero","t":"zero: F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#","e":false,"i":"","n":"F","t":"F","d":"org.appliedtopology.tda4s.Field","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#apply-d26","e":false,"i":"","n":"apply","t":"apply(t: Field.this.T): Field.this.F","d":"org.appliedtopology.tda4s.Field.F","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#fromInt-aba","e":false,"i":"","n":"fromInt","t":"fromInt(n: Int): Field.this.F","d":"org.appliedtopology.tda4s.Field.F","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#unapply-fffffb50","e":false,"i":"","n":"unapply","t":"unapply(t: Field.this.F): Option[Field.this.T]","d":"org.appliedtopology.tda4s.Field.F","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#","e":false,"i":"","n":"FiniteFieldIsField","t":"FiniteFieldIsField(val p: Int) extends Field[Int]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#add-f47","e":false,"i":"","n":"add","t":"add(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#div-f47","e":false,"i":"","n":"div","t":"div(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#inv-fffffbe0","e":false,"i":"","n":"inv","t":"inv(x: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#mul-f47","e":false,"i":"","n":"mul","t":"mul(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#neg-fffffbe0","e":false,"i":"","n":"neg","t":"neg(x: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#one-0","e":false,"i":"","n":"one","t":"one: F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#p-0","e":false,"i":"","n":"p","t":"p: Int","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#pow-f47","e":false,"i":"","n":"pow","t":"pow(x: F, n: Int): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#repAdd-f47","e":false,"i":"","n":"repAdd","t":"repAdd(x: F, n: Int): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#sub-f47","e":false,"i":"","n":"sub","t":"sub(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#zero-0","e":false,"i":"","n":"zero","t":"zero: F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#","e":false,"i":"","n":"HelixDelaunay","t":"HelixDelaunay(pts: Seq[Array[Double]])(using epsilon: Epsilon) extends SimplexStream","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#addFrontierCase-37e","e":false,"i":"","n":"addFrontierCase","t":"addFrontierCase(simplex: DelaunaySimplex, complement: Int): Unit","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#ambientDimension-0","e":false,"i":"","n":"ambientDimension","t":"ambientDimension: Int","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#candidate-0","e":false,"i":"","n":"candidate","t":"candidate: ArrayDeque[Simplex]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#computeFVal-cf5","e":false,"i":"","n":"computeFVal","t":"computeFVal(s: Simplex): Double","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#cospherical-0","e":false,"i":"","n":"cospherical","t":"cospherical: Set[Set[Int]]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#edgeIsDelaunay-999","e":false,"i":"","n":"edgeIsDelaunay","t":"edgeIsDelaunay(s: Simplex): Option[Double]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#frontierCases-0","e":false,"i":"","n":"frontierCases","t":"frontierCases: LinkedBlockingDeque[FrontierCase]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#handleCosphericalPoints-46","e":false,"i":"","n":"handleCosphericalPoints","t":"handleCosphericalPoints(cosphericalPoints: Seq[Int], frontierCase: FrontierCase, newDelaunaySimplex: DelaunaySimplex): Unit","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#points-0","e":false,"i":"","n":"points","t":"points: Seq[Point]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#seedDelaunaySimplex-0","e":false,"i":"","n":"seedDelaunaySimplex","t":"seedDelaunaySimplex: DelaunaySimplex","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#simplicesMap-0","e":false,"i":"","n":"simplicesMap","t":"simplicesMap: Map[Int, Seq[Simplex]]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#simplicesSortedMap-0","e":false,"i":"","n":"simplicesSortedMap","t":"simplicesSortedMap: Map[Int, Seq[Simplex]]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#startingSimplex-0","e":false,"i":"","n":"startingSimplex","t":"startingSimplex: Set[Int]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"var","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#validated-0","e":false,"i":"","n":"validated","t":"validated: Set[DelaunaySimplex]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay.html#visitedFacets-0","e":false,"i":"","n":"visitedFacets","t":"visitedFacets: Set[Simplex]","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay$FrontierCase.html#","e":false,"i":"","n":"FrontierCase","t":"FrontierCase(facet: Simplex, hyperplane: Hyperplane, complement: Int, cofacetHypersphere: Hypersphere)","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay$FrontierCase$.html#","e":false,"i":"","n":"FrontierCase","t":"FrontierCase","d":"org.appliedtopology.tda4s.HelixDelaunay","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/HelixDelaunay$FrontierCase$.html#apply-602","e":false,"i":"","n":"apply","t":"apply(cofacet: DelaunaySimplex, complement: Int): HelixDelaunay.this.FrontierCase","d":"org.appliedtopology.tda4s.HelixDelaunay.FrontierCase","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hyperplane.html#","e":false,"i":"","n":"Hyperplane","t":"Hyperplane(normal: Point, offset: Double)","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Hyperplane.html#dist-8c4","e":false,"i":"","n":"dist","t":"dist(point: Point): Double","d":"org.appliedtopology.tda4s.Hyperplane","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hyperplane.html#isLight-d95","e":false,"i":"","n":"isLight","t":"isLight(point: Point): Boolean","d":"org.appliedtopology.tda4s.Hyperplane","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hyperplane.html#reverse-0","e":false,"i":"","n":"reverse","t":"reverse: Hyperplane","d":"org.appliedtopology.tda4s.Hyperplane","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hyperplane$.html#","e":false,"i":"","n":"Hyperplane","t":"Hyperplane","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Hyperplane$.html#from-bcf","e":false,"i":"","n":"from","t":"from(pointSet: Seq[Point])(using epsilon: Epsilon): Hyperplane","d":"org.appliedtopology.tda4s.Hyperplane","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hypersphere.html#","e":false,"i":"","n":"Hypersphere","t":"Hypersphere(center: Point, radius: Double)(using epsilon: Epsilon)","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Hypersphere.html#contains-d95","e":false,"i":"","n":"contains","t":"contains(point: Point): Boolean","d":"org.appliedtopology.tda4s.Hypersphere","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hypersphere.html#onSphere-d95","e":false,"i":"","n":"onSphere","t":"onSphere(point: Point): Boolean","d":"org.appliedtopology.tda4s.Hypersphere","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Hypersphere$.html#","e":false,"i":"","n":"Hypersphere","t":"Hypersphere","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Hypersphere$.html#apply-744","e":false,"i":"","n":"apply","t":"apply(pointSet: Seq[Point]): Hypersphere","d":"org.appliedtopology.tda4s.Hypersphere","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace.html#","e":false,"i":"","n":"MetricSpace","t":"MetricSpace[T]","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace.html#distance-fffffdbf","e":false,"i":"","n":"distance","t":"distance(x: T, y: T): Double","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace.html#elements-0","e":false,"i":"","n":"elements","t":"elements: Seq[T]","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace$.html#","e":false,"i":"","n":"MetricSpace","t":"MetricSpace","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace$.html#fromDistanceMatrix-14f","e":false,"i":"","n":"fromDistanceMatrix","t":"fromDistanceMatrix(matrix: Array[Array[Double]]): MetricSpace[Int]","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace$.html#fromPoints-5fc","e":false,"i":"","n":"fromPoints","t":"fromPoints(points: Seq[Array[Double]], metricName: String = ...): MetricSpace[Int]","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#","e":false,"i":"","n":"NaivePersistentHomology","t":"NaivePersistentHomology[T](simplexstream: Iterator[Simplex], filtrationValues: PartialFunction[Simplex, Double])(using field: Field[T])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#barcode-0","e":false,"i":"","n":"barcode","t":"barcode: Seq[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#barcodes-0","e":false,"i":"","n":"barcodes","t":"barcodes: ListBuffer[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#filtrationValue-cf5","e":false,"i":"","n":"filtrationValue","t":"filtrationValue(simplex: Simplex): Double","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#state-0","e":false,"i":"","n":"state","t":"state: State","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"var","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#step-3a8","e":false,"i":"","n":"step","t":"step(simplex: Simplex): Unit","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#streamOrdering-0","e":false,"i":"","n":"streamOrdering","t":"streamOrdering: Ordering[Simplex]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology$State.html#","e":false,"i":"","n":"State","t":"State(cycleBasis: Map[Simplex, Chain[NaivePersistentHomology.this.T]], boundaryBasis: Map[Simplex, Chain[NaivePersistentHomology.this.T]], coboundaryLookup: Map[Simplex, Chain[NaivePersistentHomology.this.T]], cycleBirths: Map[Simplex, Double])","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/NaiveVietorisRips.html#","e":false,"i":"","n":"NaiveVietorisRips","t":"NaiveVietorisRips(metricSpace: MetricSpace[Int]) extends VietorisRips","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/PersistentHomology$.html#","e":false,"i":"","n":"PersistentHomology","t":"PersistentHomology","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/PersistentHomology$.html#persistentHomology-fffff1cf","e":false,"i":"","n":"persistentHomology","t":"persistentHomology[T](simplexStream: Iterator[Simplex], filtrationValues: PartialFunction[Simplex, Double])(using field: Field[T]): Seq[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.PersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Point$.html#","e":false,"i":"","n":"Point","t":"Point","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Point$.html#apply-a6","e":false,"i":"","n":"apply","t":"apply(coords: Array[Double]): Point","d":"org.appliedtopology.tda4s.Point","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#","e":false,"i":"","n":"QuadProgAlpha","t":"QuadProgAlpha(pts: Seq[Array[Double]], maxDistance: Double = ...) extends SimplexStream","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#Point-0","e":false,"i":"","n":"Point","t":"Point = Array[Double]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#filtrationValues-0","e":false,"i":"","n":"filtrationValues","t":"filtrationValues: Map[Simplex, Double]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#graph-0","e":false,"i":"","n":"graph","t":"graph: Map[Int, Set[Int]]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#maxd-0","e":false,"i":"","n":"maxd","t":"maxd: Double","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#metric-0","e":false,"i":"","n":"metric","t":"metric: EuclideanPointDistance","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#nnc-0","e":false,"i":"","n":"nnc","t":"nnc: NearestNeighborComputation[Int]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"var","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#pointMetric-0","e":false,"i":"","n":"pointMetric","t":"pointMetric: EuclideanDistance","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#points-0","e":false,"i":"","n":"points","t":"points: Seq[Point]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#simplexMap-0","e":false,"i":"","n":"simplexMap","t":"simplexMap: Map[Int, Seq[Simplex]]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha.html#simplicesInDimension-fffffbef","e":false,"i":"","n":"simplicesInDimension","t":"simplicesInDimension(dimension: Int): Iterator[Simplex]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha$EuclideanDistance.html#","e":false,"i":"","n":"EuclideanDistance","t":"EuclideanDistance extends Metric[Point]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/QuadProgAlpha$EuclideanPointDistance.html#","e":false,"i":"","n":"EuclideanPointDistance","t":"EuclideanPointDistance extends Metric[Int]","d":"org.appliedtopology.tda4s.QuadProgAlpha","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Ridge.html#","e":false,"i":"","n":"Ridge","t":"Ridge(normals: (Point, Point))","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Ridge$.html#","e":false,"i":"","n":"Ridge","t":"Ridge","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Ridge$.html#apply-fffffbdc","e":false,"i":"","n":"apply","t":"apply(pointSet: Seq[Point], hyperplane: Hyperplane): Ridge","d":"org.appliedtopology.tda4s.Ridge","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/SVG$.html#","e":false,"i":"","n":"SVG","t":"SVG","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/SVG$.html#plotComplex-fffff17b","e":false,"i":"","n":"plotComplex","t":"plotComplex(simplices: Seq[Simplex], positions: Seq[Array[Double]]): String","d":"org.appliedtopology.tda4s.SVG","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#","e":false,"i":"","n":"Simplex","t":"Simplex(vertices: SortedSet[Int])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#+-f15","e":false,"i":"","n":"+","t":"+(vertex: Int): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#--f15","e":false,"i":"","n":"-","t":"-(vertex: Int): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#boundary-ffffffa8","e":false,"i":"","n":"boundary","t":"boundary[T](ordering: Ordering[Simplex])(using field: Field[T]): Chain[T]","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#dimension-0","e":false,"i":"","n":"dimension","t":"dimension: Int","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#","e":false,"i":"","n":"Simplex","t":"Simplex","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#apply-fffff491","e":false,"i":"","n":"apply","t":"apply(vertices: Int*): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#from-252","e":false,"i":"","n":"from","t":"from[T <: IterableOnce[Int]](vertices: T): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#unapply-999","e":false,"i":"","n":"unapply","t":"unapply(simplex: Simplex): Option[SortedSet[Int]]","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#unapplySeq-999","e":false,"i":"","n":"unapplySeq","t":"unapplySeq(simplex: Simplex): Option[Seq[Int]]","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/SimplexStream.html#","e":false,"i":"","n":"SimplexStream","t":"SimplexStream","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/SimplexStream.html#filtrationValues-0","e":false,"i":"","n":"filtrationValues","t":"filtrationValues: PartialFunction[Simplex, Double]","d":"org.appliedtopology.tda4s.SimplexStream","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/SimplexStream.html#simplices-fffff136","e":false,"i":"","n":"simplices","t":"simplices(): Iterator[Simplex]","d":"org.appliedtopology.tda4s.SimplexStream","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/SimplexStream.html#simplicesInDimension-fffffbef","e":false,"i":"","n":"simplicesInDimension","t":"simplicesInDimension(d: Int): Iterator[Simplex]","d":"org.appliedtopology.tda4s.SimplexStream","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace.html#","e":false,"i":"","n":"VectorMetricSpace","t":"VectorMetricSpace(metric: DistanceMetric, points: Seq[Array[Double]]) extends MetricSpace[Int]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#","e":false,"i":"","n":"VectorMetricSpace","t":"VectorMetricSpace","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#DistanceMetric-0","e":false,"i":"","n":"DistanceMetric","t":"DistanceMetric = (Array[Double], Array[Double]) => Double","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#apply-78d","e":false,"i":"","n":"apply","t":"apply(metricName: String): DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#apply-fffff8f9","e":false,"i":"","n":"apply","t":"apply(metricName: String, points: Seq[Array[Double]]): VectorMetricSpace","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#correlation-0","e":false,"i":"","n":"correlation","t":"correlation: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#cosine-0","e":false,"i":"","n":"cosine","t":"cosine: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#euclidean-0","e":false,"i":"","n":"euclidean","t":"euclidean: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#hamming-0","e":false,"i":"","n":"hamming","t":"hamming: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#lp-5d9","e":false,"i":"","n":"lp","t":"lp(p: Double): DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#manhattan-0","e":false,"i":"","n":"manhattan","t":"manhattan: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#","e":false,"i":"","n":"VietorisRips","t":"VietorisRips(val metricSpace: MetricSpace[Int]) extends SimplexStream","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#filtrationValues-0","e":false,"i":"","n":"filtrationValues","t":"filtrationValues: PartialFunction[Simplex, Double]","d":"org.appliedtopology.tda4s.VietorisRips","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#metricSpace-0","e":false,"i":"","n":"metricSpace","t":"metricSpace: MetricSpace[Int]","d":"org.appliedtopology.tda4s.VietorisRips","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#simplices-fffff136","e":false,"i":"","n":"simplices","t":"simplices(): Iterator[Simplex]","d":"org.appliedtopology.tda4s.VietorisRips","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#simplicesInDimension-fffffbef","e":false,"i":"","n":"simplicesInDimension","t":"simplicesInDimension(dimension: Int): Iterator[Simplex]","d":"org.appliedtopology.tda4s.VietorisRips","k":"def","x":""}];