pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"org/appliedtopology/tda4s.html#","e":false,"i":"","n":"org.appliedtopology.tda4s","t":"org.appliedtopology.tda4s","d":"","k":"package","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#","e":false,"i":"","n":"Chain","t":"Chain[T](using val field: Field[T])(val simplexCoefficients: SortedMap[Simplex, field.F])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#field-0","e":false,"i":"","n":"field","t":"field: Field[T]","d":"org.appliedtopology.tda4s.Chain","k":"given","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#isZero-0","e":false,"i":"","n":"isZero","t":"isZero: Boolean","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#leading-0","e":false,"i":"","n":"leading","t":"leading: Option[(Simplex, field.F)]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#scale-fffff0a4","e":false,"i":"","n":"scale","t":"scale(scalingFactor: field.F): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#scaleAdd-773","e":false,"i":"","n":"scaleAdd","t":"scaleAdd(scalingFactor: field.F, other: Chain[T]): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain.html#simplexCoefficients-0","e":false,"i":"","n":"simplexCoefficients","t":"simplexCoefficients: SortedMap[Simplex, field.F]","d":"org.appliedtopology.tda4s.Chain","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#","e":false,"i":"","n":"Chain","t":"Chain","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#from-ffffffce","e":false,"i":"","n":"from","t":"from[T](simplex: Simplex)(ordering: Ordering[Simplex])(using field: Field[T]): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#from-2cf","e":false,"i":"","n":"from","t":"from[T](using field: Field[T])(terms: (Simplex, field.F)*)(using ordering: Ordering[Simplex]): Chain[T]","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Chain$.html#reduce-fffff2e8","e":false,"i":"","n":"reduce","t":"reduce[T](chain: Chain[T], basis: Map[Simplex, Chain[T]])(using outerField: Field[T]): (Chain[T], Map[Simplex, outerField.F])","d":"org.appliedtopology.tda4s.Chain","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DistanceMatrixMetricSpace.html#","e":false,"i":"","n":"DistanceMatrixMetricSpace","t":"DistanceMatrixMetricSpace(matrix: Array[Array[Double]]) extends MetricSpace[Int]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#","e":false,"i":"","n":"DoubleIsField","t":"DoubleIsField(val eps: Double) extends Field[Double]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#add-44b","e":false,"i":"","n":"add","t":"add(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#div-44b","e":false,"i":"","n":"div","t":"div(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#eps-0","e":false,"i":"","n":"eps","t":"eps: Double","d":"org.appliedtopology.tda4s.DoubleIsField","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#inv-5b2","e":false,"i":"","n":"inv","t":"inv(x: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#mul-44b","e":false,"i":"","n":"mul","t":"mul(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#neg-5b2","e":false,"i":"","n":"neg","t":"neg(x: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#one-0","e":false,"i":"","n":"one","t":"one: F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#pow-647","e":false,"i":"","n":"pow","t":"pow(x: F, n: Int): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#repAdd-647","e":false,"i":"","n":"repAdd","t":"repAdd(x: F, n: Int): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#sub-44b","e":false,"i":"","n":"sub","t":"sub(x: F, y: F): F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/DoubleIsField.html#zero-0","e":false,"i":"","n":"zero","t":"zero: F","d":"org.appliedtopology.tda4s.DoubleIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#","e":false,"i":"","n":"Field","t":"Field[T]","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#*-fffffab9","e":false,"i":"extension (x: F)","n":"*","t":"*(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#*-fffffc87","e":false,"i":"extension (x: F)","n":"*","t":"*(n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#**-fffffc87","e":false,"i":"extension (x: F)","n":"**","t":"**(n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#+-fffffab9","e":false,"i":"extension (x: F)","n":"+","t":"+(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#--fffffab9","e":false,"i":"extension (x: F)","n":"-","t":"-(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#/-fffffab9","e":false,"i":"extension (x: F)","n":"/","t":"/(y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#F-0","e":false,"i":"","n":"F","t":"F","d":"org.appliedtopology.tda4s.Field","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#add-fffffab9","e":false,"i":"","n":"add","t":"add(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#div-fffffab9","e":false,"i":"","n":"div","t":"div(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#equiv-fffff7fa","e":false,"i":"","n":"equiv","t":"equiv(x: F, y: F): Boolean","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#inv-d26","e":false,"i":"","n":"inv","t":"inv(x: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#isZero-4ad","e":false,"i":"","n":"isZero","t":"isZero(x: F): Boolean","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#mul-fffffab9","e":false,"i":"","n":"mul","t":"mul(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#neg-d26","e":false,"i":"","n":"neg","t":"neg(x: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#normalize-d26","e":false,"i":"","n":"normalize","t":"normalize(x: T): T","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#one-0","e":false,"i":"","n":"one","t":"one: F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#pow-fffffc87","e":false,"i":"","n":"pow","t":"pow(x: F, n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#repAdd-fffffc87","e":false,"i":"","n":"repAdd","t":"repAdd(x: F, n: Int): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#show-9f8","e":false,"i":"","n":"show","t":"show(x: F): String","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#sub-fffffab9","e":false,"i":"","n":"sub","t":"sub(x: F, y: F): F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#unary_--d26","e":false,"i":"extension (x: F)","n":"unary_-","t":"unary_-: F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field.html#zero-0","e":false,"i":"","n":"zero","t":"zero: F","d":"org.appliedtopology.tda4s.Field","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#","e":false,"i":"","n":"F","t":"F","d":"org.appliedtopology.tda4s.Field","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#apply-d26","e":false,"i":"","n":"apply","t":"apply(t: Field.this.T): Field.this.F","d":"org.appliedtopology.tda4s.Field.F","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#fromInt-aba","e":false,"i":"","n":"fromInt","t":"fromInt(n: Int): Field.this.F","d":"org.appliedtopology.tda4s.Field.F","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Field$F$.html#unapply-fffffb50","e":false,"i":"","n":"unapply","t":"unapply(t: Field.this.F): Option[Field.this.T]","d":"org.appliedtopology.tda4s.Field.F","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#","e":false,"i":"","n":"FiniteFieldIsField","t":"FiniteFieldIsField(val p: Int) extends Field[Int]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#add-f47","e":false,"i":"","n":"add","t":"add(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#div-f47","e":false,"i":"","n":"div","t":"div(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#inv-fffffbe0","e":false,"i":"","n":"inv","t":"inv(x: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#mul-f47","e":false,"i":"","n":"mul","t":"mul(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#neg-fffffbe0","e":false,"i":"","n":"neg","t":"neg(x: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#one-0","e":false,"i":"","n":"one","t":"one: F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#p-0","e":false,"i":"","n":"p","t":"p: Int","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#pow-f47","e":false,"i":"","n":"pow","t":"pow(x: F, n: Int): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#repAdd-f47","e":false,"i":"","n":"repAdd","t":"repAdd(x: F, n: Int): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#sub-f47","e":false,"i":"","n":"sub","t":"sub(x: F, y: F): F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/FiniteFieldIsField.html#zero-0","e":false,"i":"","n":"zero","t":"zero: F","d":"org.appliedtopology.tda4s.FiniteFieldIsField","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace.html#","e":false,"i":"","n":"MetricSpace","t":"MetricSpace[T]","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace.html#distance-fffffdbf","e":false,"i":"","n":"distance","t":"distance(x: T, y: T): Double","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace.html#elements-0","e":false,"i":"","n":"elements","t":"elements: Seq[T]","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace$.html#","e":false,"i":"","n":"MetricSpace","t":"MetricSpace","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace$.html#fromDistanceMatrix-14f","e":false,"i":"","n":"fromDistanceMatrix","t":"fromDistanceMatrix(matrix: Array[Array[Double]]): MetricSpace[Int]","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/MetricSpace$.html#fromPoints-5fc","e":false,"i":"","n":"fromPoints","t":"fromPoints(points: Seq[Array[Double]], metricName: String = ...): MetricSpace[Int]","d":"org.appliedtopology.tda4s.MetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#","e":false,"i":"","n":"NaivePersistentHomology","t":"NaivePersistentHomology[T](simplexstream: Iterator[Simplex], filtrationValues: PartialFunction[Simplex, Double])(using field: Field[T])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#barcode-0","e":false,"i":"","n":"barcode","t":"barcode: Seq[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#barcodes-0","e":false,"i":"","n":"barcodes","t":"barcodes: ListBuffer[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#filtrationValue-cf5","e":false,"i":"","n":"filtrationValue","t":"filtrationValue(simplex: Simplex): Double","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#state-0","e":false,"i":"","n":"state","t":"state: State","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"var","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#step-3a8","e":false,"i":"","n":"step","t":"step(simplex: Simplex): Unit","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology.html#streamOrdering-0","e":false,"i":"","n":"streamOrdering","t":"streamOrdering: Ordering[Simplex]","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/NaivePersistentHomology$State.html#","e":false,"i":"","n":"State","t":"State(cycleBasis: Map[Simplex, Chain[NaivePersistentHomology.this.T]], boundaryBasis: Map[Simplex, Chain[NaivePersistentHomology.this.T]], coboundaryLookup: Map[Simplex, Chain[NaivePersistentHomology.this.T]], cycleBirths: Map[Simplex, Double])","d":"org.appliedtopology.tda4s.NaivePersistentHomology","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/NaiveVietorisRips.html#","e":false,"i":"","n":"NaiveVietorisRips","t":"NaiveVietorisRips(metricSpace: MetricSpace[Int]) extends VietorisRips","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/PersistentHomology$.html#","e":false,"i":"","n":"PersistentHomology","t":"PersistentHomology","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/PersistentHomology$.html#persistentHomology-fffff1cf","e":false,"i":"","n":"persistentHomology","t":"persistentHomology[T](simplexStream: Iterator[Simplex], filtrationValues: PartialFunction[Simplex, Double])(using field: Field[T]): Seq[(Int, Double, Double)]","d":"org.appliedtopology.tda4s.PersistentHomology","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#","e":false,"i":"","n":"Simplex","t":"Simplex(vertices: SortedSet[Int])","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#--f15","e":false,"i":"","n":"-","t":"-(vertex: Int): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#boundary-ffffffa8","e":false,"i":"","n":"boundary","t":"boundary[T](ordering: Ordering[Simplex])(using field: Field[T]): Chain[T]","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex.html#dimension-0","e":false,"i":"","n":"dimension","t":"dimension: Int","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#","e":false,"i":"","n":"Simplex","t":"Simplex","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#apply-fffff491","e":false,"i":"","n":"apply","t":"apply(vertices: Int*): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#from-fffff491","e":false,"i":"","n":"from","t":"from(vertices: Seq[Int]): Simplex","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#unapply-999","e":false,"i":"","n":"unapply","t":"unapply(simplex: Simplex): Option[SortedSet[Int]]","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/Simplex$.html#unapplySeq-999","e":false,"i":"","n":"unapplySeq","t":"unapplySeq(simplex: Simplex): Option[Seq[Int]]","d":"org.appliedtopology.tda4s.Simplex","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace.html#","e":false,"i":"","n":"VectorMetricSpace","t":"VectorMetricSpace(metric: DistanceMetric, points: Seq[Array[Double]]) extends MetricSpace[Int]","d":"org.appliedtopology.tda4s","k":"class","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#","e":false,"i":"","n":"VectorMetricSpace","t":"VectorMetricSpace","d":"org.appliedtopology.tda4s","k":"object","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#DistanceMetric-0","e":false,"i":"","n":"DistanceMetric","t":"DistanceMetric = (Array[Double], Array[Double]) => Double","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"type","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#apply-78d","e":false,"i":"","n":"apply","t":"apply(metricName: String): DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#apply-fffff8f9","e":false,"i":"","n":"apply","t":"apply(metricName: String, points: Seq[Array[Double]]): VectorMetricSpace","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#correlation-0","e":false,"i":"","n":"correlation","t":"correlation: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#cosine-0","e":false,"i":"","n":"cosine","t":"cosine: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#euclidean-0","e":false,"i":"","n":"euclidean","t":"euclidean: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#hamming-0","e":false,"i":"","n":"hamming","t":"hamming: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#lp-5d9","e":false,"i":"","n":"lp","t":"lp(p: Double): DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VectorMetricSpace$.html#manhattan-0","e":false,"i":"","n":"manhattan","t":"manhattan: DistanceMetric","d":"org.appliedtopology.tda4s.VectorMetricSpace","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#","e":false,"i":"","n":"VietorisRips","t":"VietorisRips(val metricSpace: MetricSpace[Int])","d":"org.appliedtopology.tda4s","k":"trait","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#filtrationValues-0","e":false,"i":"","n":"filtrationValues","t":"filtrationValues: PartialFunction[Simplex, Double]","d":"org.appliedtopology.tda4s.VietorisRips","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#metricSpace-0","e":false,"i":"","n":"metricSpace","t":"metricSpace: MetricSpace[Int]","d":"org.appliedtopology.tda4s.VietorisRips","k":"val","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#simplices-fffff136","e":false,"i":"","n":"simplices","t":"simplices(): Iterator[Simplex]","d":"org.appliedtopology.tda4s.VietorisRips","k":"def","x":""},
{"l":"org/appliedtopology/tda4s/VietorisRips.html#simplicesInDimension-fffffbef","e":false,"i":"","n":"simplicesInDimension","t":"simplicesInDimension(dimension: Int): Iterator[Simplex]","d":"org.appliedtopology.tda4s.VietorisRips","k":"def","x":""}];